//! Build-script: parse FIX dictionary XML files and emit a Rust module per
//! dictionary, each exposing compile-time lookup tables for field names,
//! field types, enum value labels, and MsgType names.
//!
//! The generated file is `$OUT_DIR/dict_generated.rs`, included from
//! `src/generated.rs`. Each dictionary lives in its own `mod { ... }` block.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

use quick_xml::Reader;
use quick_xml::events::Event;

/// Dictionaries to generate. `module` is the Rust module name emitted into
/// the output file; `xml` is the filename inside `dictionaries/`.
const DICTIONARIES: &[(&str, &str)] = &[
    ("fix44", "FIX44.xml"),
    ("fixt11", "FIXT11.xml"),
    ("fix50sp2", "FIX50SP2.xml"),
];

struct FieldInfo {
    tag: u32,
    name: String,
    ty: String,
    // (raw enum value as it appears in the wire, human-readable label)
    values: Vec<(String, String)>,
}

struct MessageInfo {
    msgtype: String,
    name: String,
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let out =
        PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR not set")).join("dict_generated.rs");
    let mut w =
        fs::File::create(&out).unwrap_or_else(|e| panic!("creating {}: {e}", out.display()));

    let _ = writeln!(w, "// @generated by fixlog-dict/build.rs — do not edit.\n");

    for (module, xml_name) in DICTIONARIES {
        let xml_path = workspace_dict_path(xml_name);
        println!("cargo:rerun-if-changed={}", xml_path.display());

        let xml = fs::read_to_string(&xml_path)
            .unwrap_or_else(|e| panic!("reading {}: {e}", xml_path.display()));

        let (fields, messages) = parse_dictionary(&xml);
        emit_module(&mut w, module, xml_name, &fields, &messages);
    }
}

fn workspace_dict_path(name: &str) -> PathBuf {
    // CARGO_MANIFEST_DIR points at crates/fixlog-dict; dictionaries live at the workspace root.
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    manifest_dir.join("../../dictionaries").join(name)
}

fn parse_dictionary(xml: &str) -> (BTreeMap<u32, FieldInfo>, Vec<MessageInfo>) {
    let mut reader = Reader::from_str(xml);
    reader.config_mut().trim_text(true);

    let mut fields: BTreeMap<u32, FieldInfo> = BTreeMap::new();
    let mut messages: Vec<MessageInfo> = Vec::new();

    // State: we only care about <field> elements directly under <fields> (global field defs),
    // and <message> elements under <messages>. Nested <field> inside messages/components/groups
    // don't carry number/type, so we skip them.
    let mut in_fields_section = false;
    let mut in_messages_section = false;
    let mut current_field: Option<FieldInfo> = None;

    let mut buf = Vec::new();
    loop {
        match reader.read_event_into(&mut buf) {
            Ok(Event::Start(e)) => {
                let tag = e.name();
                match tag.as_ref() {
                    b"fields" => in_fields_section = true,
                    b"messages" => in_messages_section = true,
                    b"field" if in_fields_section => {
                        if let Some(info) = field_from_attrs(&e) {
                            current_field = Some(info);
                        }
                    }
                    b"message" if in_messages_section => {
                        if let Some(m) = message_from_attrs(&e) {
                            messages.push(m);
                        }
                    }
                    _ => {}
                }
            }
            Ok(Event::Empty(e)) => {
                let tag = e.name();
                match tag.as_ref() {
                    b"field" if in_fields_section => {
                        if let Some(info) = field_from_attrs(&e) {
                            fields.insert(info.tag, info);
                        }
                    }
                    b"message" if in_messages_section => {
                        if let Some(m) = message_from_attrs(&e) {
                            messages.push(m);
                        }
                    }
                    b"value" => {
                        if let Some(current) = current_field.as_mut()
                            && let Some((e_str, desc)) = value_from_attrs(&e)
                        {
                            current.values.push((e_str, desc));
                        }
                    }
                    _ => {}
                }
            }
            Ok(Event::End(e)) => match e.name().as_ref() {
                b"fields" => in_fields_section = false,
                b"messages" => in_messages_section = false,
                b"field" if in_fields_section => {
                    if let Some(info) = current_field.take() {
                        fields.insert(info.tag, info);
                    }
                }
                _ => {}
            },
            Ok(Event::Eof) => break,
            Err(e) => panic!(
                "xml parse error at position {}: {e}",
                reader.buffer_position()
            ),
            _ => {}
        }
        buf.clear();
    }

    (fields, messages)
}

fn field_from_attrs(e: &quick_xml::events::BytesStart<'_>) -> Option<FieldInfo> {
    let mut tag: Option<u32> = None;
    let mut name: Option<String> = None;
    let mut ty: Option<String> = None;
    for attr in e.attributes().flatten() {
        match attr.key.as_ref() {
            b"number" => {
                tag = std::str::from_utf8(&attr.value)
                    .ok()
                    .and_then(|s| s.parse().ok());
            }
            b"name" => name = Some(String::from_utf8_lossy(&attr.value).into_owned()),
            b"type" => ty = Some(String::from_utf8_lossy(&attr.value).into_owned()),
            _ => {}
        }
    }
    Some(FieldInfo {
        tag: tag?,
        name: name?,
        ty: ty.unwrap_or_else(|| "STRING".to_owned()),
        values: Vec::new(),
    })
}

fn message_from_attrs(e: &quick_xml::events::BytesStart<'_>) -> Option<MessageInfo> {
    let mut msgtype: Option<String> = None;
    let mut name: Option<String> = None;
    for attr in e.attributes().flatten() {
        match attr.key.as_ref() {
            b"msgtype" => msgtype = Some(String::from_utf8_lossy(&attr.value).into_owned()),
            b"name" => name = Some(String::from_utf8_lossy(&attr.value).into_owned()),
            _ => {}
        }
    }
    Some(MessageInfo {
        msgtype: msgtype?,
        name: name?,
    })
}

fn value_from_attrs(e: &quick_xml::events::BytesStart<'_>) -> Option<(String, String)> {
    let mut enum_v: Option<String> = None;
    let mut desc: Option<String> = None;
    for attr in e.attributes().flatten() {
        match attr.key.as_ref() {
            b"enum" => enum_v = Some(String::from_utf8_lossy(&attr.value).into_owned()),
            b"description" => desc = Some(String::from_utf8_lossy(&attr.value).into_owned()),
            _ => {}
        }
    }
    Some((enum_v?, desc?))
}

fn emit_module(
    w: &mut impl Write,
    module: &str,
    xml_name: &str,
    fields: &BTreeMap<u32, FieldInfo>,
    messages: &[MessageInfo],
) {
    let _ = writeln!(w, "// --- {module} (from {xml_name})");
    let _ = writeln!(w, "pub(crate) mod {module} {{");
    let _ = writeln!(w, "    use super::GenFieldDef;\n");

    // --- field_by_tag
    let _ = writeln!(
        w,
        "    pub(crate) fn field_by_tag(tag: u32) -> Option<&'static GenFieldDef> {{"
    );
    let _ = writeln!(w, "        match tag {{");
    for f in fields.values() {
        let _ = writeln!(
            w,
            "            {tag} => Some(&GenFieldDef {{ tag: {tag}, name: {name:?}, ty: {ty:?} }}),",
            tag = f.tag,
            name = f.name,
            ty = f.ty,
        );
    }
    let _ = writeln!(w, "            _ => None,");
    let _ = writeln!(w, "        }}");
    let _ = writeln!(w, "    }}\n");

    // --- enum_value_label
    let _ = writeln!(
        w,
        "    pub(crate) fn enum_value_label(tag: u32, value: &[u8]) -> Option<&'static str> {{"
    );
    let _ = writeln!(w, "        match tag {{");
    for f in fields.values() {
        if f.values.is_empty() {
            continue;
        }
        let _ = writeln!(w, "            {} => match value {{", f.tag);
        for (v, d) in &f.values {
            let _ = writeln!(w, "                b{v:?} => Some({d:?}),");
        }
        let _ = writeln!(w, "                _ => None,\n            }},");
    }
    let _ = writeln!(w, "            _ => None,");
    let _ = writeln!(w, "        }}");
    let _ = writeln!(w, "    }}\n");

    // --- msg_type_label
    let _ = writeln!(
        w,
        "    pub(crate) fn msg_type_label(value: &[u8]) -> Option<&'static str> {{"
    );
    let _ = writeln!(w, "        match value {{");
    let mut seen = std::collections::BTreeSet::new();
    for m in messages {
        if seen.insert(&m.msgtype) {
            let _ = writeln!(
                w,
                "            b{mt:?} => Some({name:?}),",
                mt = m.msgtype,
                name = m.name,
            );
        }
    }
    let _ = writeln!(w, "            _ => None,");
    let _ = writeln!(w, "        }}");
    let _ = writeln!(w, "    }}\n");

    let _ = writeln!(
        w,
        "    pub(crate) const FIELD_COUNT: usize = {};",
        fields.len()
    );
    let _ = writeln!(
        w,
        "    pub(crate) const MESSAGE_COUNT: usize = {};",
        messages.len()
    );
    let _ = writeln!(w, "}}\n");
}
